### ISSUE TITLE
Unnecessary dependency on OpenCV

### ISSUE THREAD

**Issue by miguelvr** [uber/petastorm#186]
I'm trying to export a non-image spark dataset to the petastorm format, and when I import the petastorm codecs, I get this:

```
~/.conda/envs/stb2/lib/python3.5/site-packages/petastorm/codecs.py in <module>()
     25 from io import BytesIO
     26 
---> 27 import cv2
     28 import numpy as np
     29 from pyspark.sql.types import BinaryType, LongType, IntegerType, ShortType, ByteType, StringType

ImportError: No module named 'cv2'
```

It doesn't make sense to keep opencv as a dependency, it seems unnecessary.

**Comment by rgruener** [comment]
So we actually define opencv as an extra dependency in the setup.py however you are correct that it isnt really extra since we force it as a dependency (we mainly defined it as extra in case people want to install older versions as a debian package instead of through pip).

Since images are such a large part of what we use petastorm for we have not done anything to make it an optional dependency, though it certainly could be and probably should be.
