### ISSUE TITLE
Reader takes a long time to exit

### ISSUE THREAD

**Issue by miguelvr** [uber/petastorm#187]
I just converted a part of my spark dataset with the petastorm utilities, and now I'm trying to print the results of a single batch.

Each row of the dataset has 2 columns, each one with a (1, 24) shaped np.ndarray

I'm using this code to print a single row:
```
    with Reader(output_url) as reader:
        for i, row in enumerate(reader):
            print(row)
            break
```

I takes a decently big amount of time to print the row, and then it takes even more time to exit the program, which is super weird.

Am I doing anything wrong?

**Comment by rgruener** [comment]
How long are we talking about? If its a few seconds that is likely normal as there is some overhead in starting and killing all the threads being spun up which immediately start reading your dataset.

We mainly optimize for read throughput so startup and shutdown time isnt something we look at too often since our main use case is long running ML model training

**Comment by miguelvr** [comment]
> How long are we talking about? If its a few seconds that is likely normal as there is some overhead in starting and killing all the threads being spun up which immediately start reading your dataset.

i'm talking about almost a minute, on start-up and shutdown

> We mainly optimize for read throughput so startup and shutdown time isnt something we look at too often since our main use case is long running ML model training

What about inference? Would petastorm be useful for inference as well, or you would suggest something else?

> More details: deserializing <1K rows is very Python processing heavy, since we loop over all rows in a rowgroup. Python threads would be ineffective since they would be waiting on GIL. ProcessPool implements a multiprocessing loading/decoding strategy and goes around the GIL issue. pyarrow_serialize=True uses a faster way of serializing data in IPC, but does not support Decimal types well, hence we don't switch it on by default.

In the current setup I have to convert columns containing lists into numpy arrays? Is there any Unischema that supports lists instead? This would avoid decoding with np.load, but it would require to convert the list into a numpy array eventually, however this could be done at the batching stage. I'm basically dealing with a time-series in each column.

**Comment by selitvin** [comment]
> What about inference? Would petastorm be useful for inference as well, or you would suggest something else?
There could be some term mixup. When you say inference, what is the exact scenario do you refer to? Are you serving your model and get incoming classification requests or are you running evaluation on an evaluation set to measure model performance? Petastorm could be useful in the latter case.

> In the current setup I have to convert columns containing lists into numpy arrays
You can derive from `DataframeColumnCodec` and implement your own codec to handle lists correctly (Petastorm is extensible in this regard), however, numpy array deserialization is much much faster comparing to standard Python list pickling, so I am not sure it's a good idea performance-wise.

**Comment by selitvin** [comment]
@miguelvr, in version 0.5.1 we added support of working with non-Petastorm Parquet files. Seems like in your case you could have two columns of `ArrayType`. If you do so, I expect you to get a very good performance if you read your data in batches using `make_petastorm_reader`. We did develop this feature for internal usage and have a good experience with it.

**Comment by cupdike** [comment]
I have seen huge shutdown times too--even why I manually try to stop the reader.  Below, 6 minutes elapses from the time the "with" context is exited and the program actually exits.  The processes running petastorm.workers_pool.exec_in_new_process do show significant CPU consumption:

```
print("##### Starting context: ", datetime.datetime.now()); sys.stdout.flush()
readerPool = ProcessPool(workers_count, PickleSerializer())
with Reader(pyarrow_filesystem=wrapped_fs, dataset_path=dataset_url, predicate=predicate, reader_pool=readerPool, num_epochs=1) as reader:
    dataset = make_petastorm_dataset(reader)

    print("##### Starting Loop:    ", datetime.datetime.now()); sys.stdout.flush()

    for sample in dataset.take(3):
        print(sample)

    print("##### Finished Loop:    ", datetime.datetime.now()); sys.stdout.flush()
    reader.stop();
    print("##### Finished Stop:    ", datetime.datetime.now()); sys.stdout.flush()

print("##### Finished context: ", datetime.datetime.now()); sys.stdout.flush()
```
```
##### Starting context:  2019-11-11 19:18:18.707111
##### Starting Loop:     2019-11-11 19:18:20.621053
##### Finished Loop:     2019-11-11 19:18:38.931877
##### Finished Stop:     2019-11-11 19:18:38.941090
##### Finished context:  2019-11-11 19:24:34.330883
```
I tried manually calling stop on the reader at the end of the with block but it didn't help.  

Any idea what is causing this huge delay from the "Finished stop" to "Finished context"?

**Comment by selitvin** [comment]
@cupdike : my guess would be that it takes a long time to finish loading/processing of a single rowgroup. We join on all worker threads/processes and they would not give up until all decoding is finished. High CPU usage hints in that this is the case.  
BTW, I see that you are using `PickleSerializer()` in `ProcessPool` construction. Did you try `PyArrowSerializer` serialization object? It maybe much faster in many cases.

**Comment by cupdike** [comment]
I did try PyArrowSerializer in other tests but it was on a machine with relatively limited RAM (16 GB).  I detailed my findings here:  https://github.com/uber/petastorm/issues/432#issuecomment-539162088
I believe it did not help (and could have made performance worse) but I suspect that may have been because of the machine size.  

I've run the number on memory usage, and I still don't understand why I hit memory limits so often.  Am I calculating something wrong here?  It seems like only around 2 GB should be used, yet I've seen all 16 GB get consumed before a crash:

`>>> np.ndarray([224,244,3], dtype='uint8').nbytes`
`163968 <= number of uncompressed bytes in the image (which dominates the row size)`

* threads: 
  * nThreads = 10
* number of rows in row group
  * nRows ~= 1200 for flow_rgb_05 (5% sampled), per: Dataset fmow_05
* results queue size
  * oq = 50
* size of sample ("row") uncompressed (in our case, effectively the numpy image array since it is huge relative to the other columns)
  * S = 164 KB

n=10
r=1200
oq=50
S=164000
sq=0
nr + S(sq+oq)  => 10*1200*164kB + 164kB(0+50) = 1968 MB + 8.2 MB => approx 2 GB

**Comment by Jomonsugi** [comment]
I am unable to find `make_petastorm_reader` anywhere in the petastorm library.

**Comment by selitvin** [comment]
Are you referring to `make_petastorm_dataset` ? Indeed, `make_petastorm_reader` does not exist.
