### ISSUE TITLE
Petastorm Pytorch DataLoader does not support multiple worker functionality

### ISSUE THREAD

**Issue by ktertikas** [uber/petastorm#240]
Hi, I am trying to use Petastorm with Pytorch to train a very simple neural network on MNIST. While reading through the source code, I noticed that the Petastorm DataLoader does not support multiple workers for data loading and, especially for the data augmentation part, the transforms are applied sequentially per row, until a batch is "filled". This can be seen in the following code snippet: 

https://github.com/uber/petastorm/blob/8fe78d3095afef1a7aa98359f32672bad23f7e17/petastorm/pytorch.py#L119-L137

On the other hand, the Petastorm Reader supports functionality for parallelization of reading data from the parquet dataset. 

Are there any plans to improve this so that the data loading after data augmentation is more efficient?

**Comment by rgruener** [comment]
We are aware of this and this is something that I am actually currently looking into (specifically allowing for preprocessing transforms to happen concurrently in order to build batches. We need to make sure by doing so however that we keep memory copying and serialization to a minimum since that would counteract the performance gains through doing that preprocessing in parallel.

If you have any suggestions let us know!

**Comment by ishaybe** [comment]
any news about this feature?

**Comment by selitvin** [comment]
It was actually implemented. Please see `transform_spec` argument of the `make_reader`/`make_batch_reader`: https://petastorm.readthedocs.io/en/latest/api.html#module-petastorm.reader
