### ISSUE TITLE
Using predicate with local cache

### ISSUE THREAD

**Issue by GregAru** [uber/petastorm#306]
Hi,

When trying to query a dataset with both predicate and cache (aka: `predicate` and `cache_location`, `cache_type`, `cache_size_limit` and `cache_row_size_estimate`) arguments provided in `make_reader`, I get the following exception:

_/petastorm/arrow_reader_worker.py", line 121, in process
    raise RuntimeError('Local cache is not supported together with predicates, '
RuntimeError: Local cache is not supported together with predicates, unless the dataset is partitioned by the column the predicate operates on._

This is extremely limiting. 
Are there plans to make cache work with the predicate?

**Comment by selitvin** [comment]
It should be fairly straight forward. (We did not have many users of cache up until now). One thing to notice though that the function needs to be a pure function. Does that hold for your usecase?

**Comment by selitvin** [comment]
I am also curious about your cache usage. Does your main store has slow connection and you expect to get better performance when reading from local cache? 
Also, would you expect the whole dataset to be cached or only rows that match the predicate?

**Comment by GregAru** [comment]
> Does your main store has slow connection and you expect to get better performance when reading from local cache?

Yes. This is exactly my issue.

I am using S3 as a data repository for the Petastorm dataset. 
When querying the dataset from an EC2 machine I get acceptable networking performance.
However, when reading from outside of AWS - the download speed is poor to the point where `make_reader` and `make_batch_reader` are practically unusable.

My aim is to have the ability to do local/fast dev with a sample of the filtered(by combination of predicate and row_group selector) dataset, and then deploy the same code to AWS to run against the full-filtered dataset. I was hoping to achieve this(create local sample of the data) by using local_cache  but got the exception above. Perhaps there is some other approach that can be used? 

Small note:  When using `make_reader` or `make_batch_reader` from outside of AWS, I get much worse performance than when just downloading the raw JPEGs via aws cli. Perhaps I am missing something in the reader configuration?

**Comment by selitvin** [comment]
Understood. There are two off-the-shelf solutions that might work in your case. To acquire a small subset of data with cache still being functional:
- Use "sharding": `make_*_reader` functions have `cur_shard` and `shard_count` arguments. To get, say 1/10 of the data you can pass `cur_shard=0`, `shard_count=10`. The split is deterministic for a given dataset instance. 
- Use only rowgroup-selector, without predicate. Cache is incompatible with predicates at the moment but compatible with rowgroup-selectors.

Would any of these solutions work for you? Regardless, we should still make predicate work with cache.

Regarding the work from outside of AWS: I don't see a reason for this to happen. Some questions:
- Do you also observe smaller network utilization than when using CLI? 
- Is the average when observed over larger time lower? (It would be not surprising if the first sample delay is much larger since the entire rowgroup needs to be downloaded from the network. Also if you have multiple threads, they would be sharing the whole bandwidth)

FYI: you can use [`petastorm-throughput.py`](https://petastorm.readthedocs.io/en/latest/benchmarks_tutorial_include.html) to easily measure throughputs when playing with various tuning parameters.

**Comment by GregAru** [comment]
I am already using the `cur_shard` and `shard_count`,  thanks. Although a simple `limit` might have been more useful, since it is more deterministic.

Using the rowgroup selector only is problematic since it will cause for some unwanted data leaking in. To avoid this as much as possible I will have to repartition/sort/... the dataset and possibly reduce the size of the row_groups. Also the filtering capabilities would be limited only to the indexed fields.  I don't think that this is something I can work with in the long term.

`* Do you also observe smaller network utilization than when using CLI?`
I mainly observe inconsistency in network utilization when compared to the CLI. Sometimes it will reach the CLI level but more often it will be much lower. I will try to reduce the row-group size(currently 128MB) and try again. 

Regarding the row_group size - in general when working with parquet and non-binary data it is common to use 128MB or more. When creating the dataset, based on `generate_petastorm_dataset.py` example I have used 256MB which caused out of memory errors with 10 workers on a 60GB-memory machine.  I have then re-created the dataset with row_group size of 128MB and reduced the number of workers to 4 which resulted in a more stable behavior.  In general, what is the optimal row_group size to be used? And how can it be calculated?

Overall, I think that it is a common scenario to be able to work with a small dataset on the side and then deploy the code to a more capable machine, close to the main data repository to do the heavy lifting. I think it will be for sure the main use-case for AWS users who use S3 and have restricted budget.

**Comment by selitvin** [comment]
We avoided implementing `limit` since it is tricky to get the same set to be returned due to a race between multiple readers, hence sharding looked like a better idea to reduce the result set size.

> out of memory errors with 10 workers on a 60GB-memory machine
Would increasing the amount of rdd partitions have any effect on the memory pressure? Something like this:
```python
    with materialize_dataset(spark, output_url, HelloWorldSchema, rowgroup_size_mb):

        rows_rdd = sc.parallelize(range(rows_count), numSlices=*** GREATER NUMBER ***)\
            .map(row_generator)\
            .map(lambda x: dict_to_spark_row(HelloWorldSchema, x))

        spark.createDataFrame(rows_rdd, HelloWorldSchema.as_spark_schema()) \
            ....
            .parquet(output_url)
```
The way pyspark is implemented, it makes the amount of memory used pretty hard to control...

I wonder, what is the compressed/uncompressed size of a row in your dataset?

> what is the optimal row_group size to be used
Besides the obvious amount of roundtrips, things to consider:
- Too large rowgroups results in high amount of RAM you spend on decorrelating samples in a shuffling queue during training. 
- Too small rowgroup sizes may increase memory consumption due to the way binary fields statistics is calculated in parquet version prior to 1.8.3 (@rgruener can you please confirm this statement is accurate?)

I would like to try this remote s3 aws scenario. We have never encountered it so maybe there are some low hanging fruits there.

Thank you very much for bringing these issues to our attention!

**Comment by GregAru** [comment]
Thanks for the reply.
The out-of-memory I got was actually when trying to read the dataset with `make_reader` - not when generating the dataset with Spark.  I got stable performance with  `make_reader` when reducing the row_group size from 256MB to 128MB and decreasing the `workers_count` in `make_reader` from the default 10 to 4. This is why I was wandering what is the recommended row_group size.   The Jpeg sizes I am trying to store  are between 300K and 500K (3 channel 1920x1080). In addition, I have a few metadata fields (up to 20) - integers or booleans mostly.

**Comment by selitvin** [comment]
One more parameter you might want to look at is the `results_queue_size=50`. This is the maximum size of the queue workers write into. If you are using a shuffling queue right after the reader (if you are using TF, then the `tf_tensors(..., shuffling_queue_capacity=`)`, then you may want to set `results_queue_size` to some low value, say 5, as two queues back to back don't provide much advantage. 

When the data is waiting in queue to be consumed, it is stored in uncompressed form. Your petastorm memory consumption by you samples can be estimated like this. Will use your numbers:
n : number of threads (10)
oq: results_queue_size (50)
sq: shuffling queue size (let's assume 1000)
S: size of a sample uncompressed (7MB)
g: number of rows in a rowgroup (in case of 256MB --> ~600 rows)
r: size of the rowgroup (uncompressed)  (600 rows * 7MB = 4800MB)

n*r + S*(sq+oq) = 48GB + 7GB ~ 56GB

which seems to be aligned with what you are reporting. 

so your adjustments make a lot of sense and should be very effective. 

In our scenarios, the throughput is usually saturated with 5 working threads, but you would need to play with your setup to discover what gives the best performance.

**Comment by GregAru** [comment]
Thank you for the thorough answer. 
With another emphasis on the importance of full functionality of the local cache - I  am closing this issue.

**Comment by selitvin** [comment]
Cool. Opened #309  to  track the fix for the issue. Thanks for bringing it up.
