### ISSUE TITLE
make_batch_reader fails with unclear assertion error

### ISSUE THREAD

**Issue by GregAru** [uber/petastorm#312]
I am experiencing the following error when trying to read an S3 dataset using make_batch_reader.
I am using the latest master. 

_lib/python3.6/site-packages/petastorm/arrow_reader_worker.py", line 50, in read_next
    assert len(column.data.chunks) == 1
AssertionError_

**Comment by selitvin** [comment]
Interesting. Only one ParquetDatasetPiece should be read at a time. I had an assumption that this guarantees only a single chunk to be allocated. Would be interesting to reproduce. Is this the same data you describe in #306? Were you be able to read the data from s3 before and something has changed?

**Comment by GregAru** [comment]
Before I was able to read a local test dataset.
This is the first time I have tried reading data using `make_batch_reader` from S3. 

Below is the code I have used to generate the dataset.
Please note that the source dataset is also a Petastorm dataset so I am reading it as is to avoid decoding/encoding.
```
TestDataset = Unischema('TestDataset', [
    UnischemaField('date', np.int32, (), ScalarCodec(IntegerType()), False),
    UnischemaField('tag', np.int32, (), ScalarCodec(IntegerType()), False),
    UnischemaField('id', np.str_, (), ScalarCodec(StringType()), False),
    UnischemaField('image', np.uint8, (1080, 1920, 3), CompressedImageCodec('jpeg'), False),
    UnischemaField('image_path', np.str_, (), ScalarCodec(StringType()), False),
])

def generate_partitioned_color_dataset(spark_: SparkSession,
                                       input_path,
                                       output_url,
                                       row_group_size=64,
                                       schema: Unischema = TestDataset):
    with materialize_dataset(spark_, output_url, schema, row_group_size):
        df = spark_.read.schema(schema.as_spark_schema()).parquet(input_path)
        df_aug = df.withColumn('date', get_date(df.id)) \
            .withColumn('image_path', get_path(df.id)) \
            .withColumn('rander', round(rand(1) * 10)) \
            .repartition('date', 'rander') \
            .drop('rander')
        df_aug.write.mode('overwrite').partitionBy('date').parquet(output_url)
    build_rowgroup_index(output_url,
                         spark.sparkContext,
                         [SingleFieldIndexer('date_idx', 'date'), SingleFieldIndexer('tag_idx', 'tag')])
```

And the code to read the data:
```
    with make_batch_reader(dataset_url=dataset_uri,
                           workers_count=workers_count,
                           predicate=predicate,
                           rowgroup_selector=row_group_selector,
                           num_epochs=1) as reader:
        for batch_num, sample_batch in enumerate(reader):
        ...
```

The reader returns the first batch and then fails with the exception above.

**Comment by selitvin** [comment]
Awesome, thanks for your example. I understand the context better. So the issue is about poor message and not that `make_batch_reader` does not work with your dataset? Risking to say something that you are already aware of, here is some background on `make_batch_reader`.

`make_batch_reader` currently supports only working with "non Petastorm" Apache Parquet stores, i.e. stores that contain only native Parquet types. `make_batch_reader` would not decode your images properly, even if the assert would not be triggered. 

Some background:
We implemented this feature, so Petastorm can be used for training from existing organizational stores and eliminate a need for an extra ETL step in these scenarios. You can use it to read datasets containing scalars and arrays only and achieves orders of magnitude better performance then a reader created with `make_reader`. 

Since in your case you have images and it is likely that most of the loading time is spent on decoding of these images, the benefits of `make_batch_reader` would not be significant.

We will add a fix that would alert against using `make_batch_reader` on datasets with columns that require non-trivial decoding, like in your case.

**Comment by GregAru** [comment]
I am actually fine with not decoding the images.
My goal was to allow to download a sample of images in their source format (jpeg, png).
Together with the metadata as CSV or Json. I was hoping to use `make_batch_reader` to avoid the memory usage for decoding/encoding and writing additional code on my end. 
But I guess I can use `make_reader` instead.
