### ISSUE TITLE
UnischemaField name field cannot set `name` value 

### ISSUE THREAD

**Issue by wangqiaoshi** [uber/petastorm#327]
code:
test_schema = Unischema('test_schema', [
    ...:         UnischemaField('id', np.int32, (), ScalarCodec(IntegerType()), False),
    ...:         UnischemaField('name', np.string, (), ScalarCodec(StringType()), False)
    ...:     ])

error:
 114         # Generates attributes named by the field names as an access syntax sugar.
    115         for f in fields:
--> 116             setattr(self, f.name, f)
    117 
    118     def create_schema_view(self, fields):

AttributeError: can't set attribute

**Comment by selitvin** [comment]
This is due to a conflict with the `name` property of the `Unischema` object itself. 
Dynamic property names were created as a syntax sugar and is widely used in our codebase.

Suggest the following solution:
- Rename current `name` property to `_name`. This pattern is used by `collections.namedtuple`, I suspect for the same reason. The rename would reduce a probability of a conflict since `name` is a common column name.
- Issue a warning if a conflict is detected with other properties (e.g. `fields`). Don't create a dynamic property and don't raise an error (just warning).

**Comment by selitvin** [comment]
Created PR #328 to address this issue

**Comment by selitvin** [comment]
77727b0b5be2b4587eb2a10f570e8849ec6122f8 properly solves this issue.
